// src/frontend/components/views/Top.svelte
<script type="ts">
  import T from "../helpers/T.svelte"
  import type { TopViews } from "../../../types/Views"

  export let mode: TopViews

  // let settings = false
</script>

<!-- <button on:click={() => (settings = !settings)}>
  <T id="menus.settings" />
  {translate('menus.settings', $language)}
  {translate(d.menus?.settings)}
</button> -->

<div>
  <span>
    <button title="Switch to live view" on:click={() => (mode = "live")}>Live</button>
    <button title="Go to editor" on:click={() => (mode = "edit")}>Edit</button>
    <button title="Go to stage" on:click={() => (mode = "stage")}>Stage</button>
  </span>
  <span>
    <button title="Settings" on:click={() => (mode = "settings")}><T id="menus.settings" /></button>
  </span>
</div>

// src/components/Top.jsx
export default function Top({setMode, mode}) {
  return (
    <div style={{boxShadow: '2px 2px 4px 0 rgb(0 0 0 / 40%)', zIndex: 9999, padding: '10px'}}>
      <button title="Switch to live view" style={(mode === 'live' ? {color: 'var(--secondary)'} : {})} onClick={() => setMode('live')}>Live</button>
      <button title="Go to editor" style={(mode === 'edit' ? {color: 'var(--secondary)'} : {})} onClick={() => setMode('edit')}>Edit</button>
      {/* <button>X</button> */}

      <span style={{position: 'absolute', right: 10}}>
        <button>Settings</button>
        <button>About</button>
      </span>
    </div>
  );
}
